version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "5000:80"
    links:
      - redis

  redis:
    image: redis:alpine

  worker:
    build: ./worker
    links: 
      - redis
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  result:
    build: ./result
    command: nodemon server.js
    ports:
      - "5001:80"
    links: 
      - db
